### PR TITLE
Allow access to data/disks mounted in /mnt and /srv

### PR DESCRIPTION
**Pull request by ximion**
This should resolve https://github.com/flathub/org.libvips.vipsdisp/issues/2

### CODE REVIEW

**Comment by jcupitt** [comment]
Thanks!

**Comment by hfiguiere** [comment]
what wrong with using Flatseal to configure this with your non standard path?

Basically you just loosened everyone security for your custom setup.

**Comment by ximion** [comment]
> Basically you just loosened everyone security for your custom setup.

I think this is an extremely common setup in scientific institutions. Since this app already has full rw access to /home, allowing access to /mnt doesn't really reduce security in any meaningful way (there will always be permissions preventing apps to write in locations they shouldn't write to).
We also often automatically deploy tools like this on a lot of machines, I'm not sure it Flatseal can be automated... (probably, haven't looked into that yet tbh)
Also, since this setup is so incredibly common (basically 100% of Linux-using labs in our department as well as the high performance cluster systems) it would just be nice if people who casually install this app could use it immediately on their data, instead of going through a bunch of extra steps that they almost certainly don't know about.

**Comment by hfiguiere** [comment]
> We also often automatically deploy tools like this on a lot of machines, I'm not sure it Flatseal can be automated... (probably, haven't looked into that yet tbh)

`man flatpak-override`

Flatseal is just a GUI.

**Comment by ximion** [comment]
I'm actually thinking of proposing a new permission setting that allows access to some common locations for read/write access to users, like /mnt, in addition to user's home directories. Having network drives or even just permanently mounted local disks in /mnt is incredibly common, given the immensely large files we handle it would just be impractical if users copied them to $HOME every time. But I can also see that to be useful for e.g. Steam where users may want to store their library on an external drive - and at least the Clementine player Flatpak here also allows /mnt for the exact reason of people having their music library there.

The failure mode of /mnt not being accessible is also not great, I was actually very confused when drag & drop didn't work and only remembered the filesystem filtering once I didn't find the path in the app's file open dialog.

**Pull request merged**
